# Generated by Django 5.0.7 on 2024-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=150, unique=True, verbose_name='Contact ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact Name')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Updated Staus')),
            ],
            options={
                'verbose_name': 'contact_details',
                'verbose_name_plural': 'contact_details',
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=150, unique=True, verbose_name='Group ID')),
                ('group_name', models.CharField(max_length=150, verbose_name='Group Name')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Updated Staus')),
            ],
            options={
                'verbose_name': 'group_details',
                'verbose_name_plural': 'group_details',
                'db_table': 'group_details',
            },
        ),
    ]
