# Generated by Django 5.0.7 on 2024-07-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=150, unique=True, verbose_name='Chapter Name')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapter',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='ChaperGroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_integrations.groupdetails', verbose_name='Group Details')),
                ('chapter_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_integrations.chapter', verbose_name='Chapter Details')),
            ],
            options={
                'verbose_name': 'chapter_group',
                'verbose_name_plural': 'chapter_group',
                'db_table': 'chapter_group',
            },
        ),
        migrations.CreateModel(
            name='ChaperContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_integrations.contactdetails', verbose_name='Contact Details')),
                ('chapter_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_integrations.chapter', verbose_name='Chapter Details')),
            ],
            options={
                'verbose_name': 'chapter_contact',
                'verbose_name_plural': 'chapter_contact',
                'db_table': 'chapter_contact',
            },
        ),
    ]
