# Generated by Django 5.0.7 on 2024-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0002_chapter_chapergroupdetails_chapercontactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150, unique=True, verbose_name='Template Name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contect')),
            ],
            options={
                'verbose_name': 'templates',
                'verbose_name_plural': 'templates',
                'db_table': 'templates',
            },
        ),
    ]
