# Generated by Django 5.0.7 on 2024-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0003_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='Contect HTML'),
        ),
    ]
