# Generated by Django 5.0.7 on 2024-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0004_templates_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='has_excel',
            field=models.BooleanField(default=False, verbose_name='Has Excel'),
        ),
    ]
