# Generated by Django 5.0.7 on 2024-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0005_templates_has_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='has_multi_sheet',
            field=models.BooleanField(default=False, verbose_name='Has Multi Sheet'),
        ),
    ]
