# Generated by Django 5.0.7 on 2024-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0006_templates_has_multi_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='excel_image',
            field=models.BooleanField(default=False, verbose_name='Excel Image'),
        ),
    ]
