# Generated by Django 5.0.7 on 2024-08-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0007_templates_excel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='is_shortable',
            field=models.BooleanField(default=False, verbose_name='Shortable'),
        ),
    ]
