# Generated by Django 5.0.7 on 2024-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0008_templates_is_shortable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='is_shortable',
            new_name='is_sortable',
        ),
    ]
