# Generated by Django 5.0.7 on 2024-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0009_rename_is_shortable_templates_is_sortable'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='leave_row',
            field=models.BooleanField(default=False, verbose_name='Leave Row'),
        ),
    ]
