# Generated by Django 5.0.7 on 2024-09-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_integrations', '0010_templates_leave_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='has_link',
            field=models.BooleanField(default=False, verbose_name='Has Link'),
        ),
    ]
